// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/**
 * Primary content in TextImageBloc → Primary
 *
 */
interface TextImageBlocSliceDefaultPrimary {
  /**
   * image field in *TextImageBloc → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_bloc.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
  /**
   * text field in *TextImageBloc → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_bloc.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text: prismic.KeyTextField;
  /**
   * caption field in *TextImageBloc → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_bloc.primary.caption
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  caption: prismic.KeyTextField;
}
/**
 * Default variation for TextImageBloc Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextImageBlocSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextImageBlocSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *TextImageBloc*
 *
 */
type TextImageBlocSliceVariation = TextImageBlocSliceDefault;
/**
 * TextImageBloc Shared Slice
 *
 * - **API ID**: `text_image_bloc`
 * - **Description**: `TextImageBloc`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextImageBlocSlice = prismic.SharedSlice<
  "text_image_bloc",
  TextImageBlocSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client;
  }
  namespace Content {
    export type {
      TextImageBlocSliceDefaultPrimary,
      TextImageBlocSliceDefault,
      TextImageBlocSliceVariation,
      TextImageBlocSlice,
    };
  }
}
