// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  text_image_bloc: defineAsyncComponent(
    () => import("./TextImageBloc/index.vue")
  ),
});
